<a href="https://colab.research.google.com/github/kavyarajegoist/deep_learning_with_pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
### Creating Tensors
Pytorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim


0

In [7]:
#Get tensor back as Python int
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],[2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([2, 3])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[1,3,4],[2,3,3]]])
TENSOR

tensor([[[1, 2, 3],
         [1, 3, 4],
         [2, 3, 3]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 3, 4],
        [2, 3, 3]])

In [18]:
TENSOR[0][1]

tensor([1, 3, 4])

In [19]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learns as they start with tensors full of random numbers and then adjust those random numbers to better represnt the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

In [20]:
#create a random tensor of size(3,3)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7948, 0.5799, 0.5330, 0.5363],
        [0.1050, 0.6573, 0.1199, 0.6638],
        [0.5089, 0.7654, 0.2530, 0.5908]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
#Create a random tensor with similar to shape of and image tensor
random_image_size_tensor = torch.rand(size =(224,224,3) ) # height , width , color channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor


In [24]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create all tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
#Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big error you'll run into  with Pytorch & deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

Precision in computing


In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what datatype is the tensor (eg.float32))
                                  device = None,# What device is your tensor on
                               requires_grad=False) #whether or not to track gradient with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])




### Getting information from tensors
1. Tensor not right datatype. - to do get datatype from a tensor, can use 'tensor.dtype'.
2. Tensor not right shape. - to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use tensor.device






In [35]:
#Create a tensor
some_tensor = torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.8872, 0.8618, 0.0879, 0.1606],
        [0.0171, 0.3223, 0.1323, 0.6626],
        [0.0264, 0.8740, 0.3813, 0.3921]], dtype=torch.float16)

In [36]:
print(f"Data type of tensor: {some_tensor.dtype}")
print(some_tensor.shape)
print(some_tensor.device)

Data type of tensor: torch.float16
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operation)

* Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication


In [37]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor - 5

tensor([-4, -3, -2])

In [39]:
tensor * 10


tensor([10, 20, 30])

In [40]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [41]:
#Tensor inbuilt function
torch.mul(tensor,10)


tensor([10, 20, 30])

### Matrix Multiplication
Two ways of matrix multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [42]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
#Matrics Multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 672 µs, sys: 101 µs, total: 773 µs
Wall time: 6.33 ms


tensor(14)

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 385 µs, sys: 58 µs, total: 443 µs
Wall time: 636 µs


In [45]:
# Shapes for matrix multiplication
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])



To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [46]:
tensorB.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [47]:
torch.mm(tensorA,tensorB.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc.(tensor aggregation)


In [48]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [50]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [51]:
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [53]:
# Finding the positional min and max value(basically finding the index)
x.argmin()

tensor(0)

In [54]:
x.argmax()

tensor(9)

In [55]:
x[9]

tensor(90)

In [56]:
%%time
l = [1,2,3]
value = 0
for i in range(len(l)):
  value += l[i] * l[i]
print(value)

14
CPU times: user 98 µs, sys: 0 ns, total: 98 µs
Wall time: 93 µs


## Reshaping, stacking, squeezing and unsqueezing tesnors

* Reshaping - reshapes an input tensor  to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine mutiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - remove all `1` dimensions from a tensor

* Unsqueeze - adds `1` dimensions to a tensor

* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [57]:
#let create tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor share the same memory as the original tensor)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [63]:
# torch.unsqueeze() add a single dimensions to a target at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous target shpae: {x_squeezed.shape}")

x_unsqueezed = torch.unsqueeze(x_squeezed,0)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target shpae: torch.Size([9])

New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [64]:
#torch.prmute - rearranges the dimesions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # (height, width, colour_channels)
x_permuted = torch.permute(x_original,dims=(2,0,1))

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [65]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
x[0][0],x[0,0],x[0,0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]), tensor(1))

In [67]:
# Challenge to get the number 9
x[0][2][2]

tensor(9)

In [68]:
# Using ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [69]:
# Get all values of 0th dimensions but only index 1 of 2nd dimensions
x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
# Get all values of 0th dimensions but only the 1 index of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [71]:
# Get index o of 0th and 1st dimension and all values of 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

In [72]:
# index on x to return 9
x[:,2,2]

tensor([9])

In [73]:
# return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy
Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [74]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0,8.0)
tensor  = torch.from_numpy(array).type(torch.float32)

array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [75]:
# Change the value of array, what will this do to 'tensor'?
array = array +1
array,tensor


(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [76]:
# Tenosr to numpy array
tensor = torch.ones(7)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
tensor = tensor + 1

In [78]:
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again`

To reduce the randomness in neural network comes the concept of random seed

Essentially what the random seed does flavour  the randomness

Go throught the pytorch reproducibilty documentation on the pytorch website.

Wekipedia random seed

In [79]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7332, 0.4931, 0.8607, 0.6452],
        [0.4395, 0.6287, 0.9037, 0.8764],
        [0.2971, 0.7602, 0.1854, 0.6174]])
tensor([[0.9341, 0.8344, 0.2709, 0.1286],
        [0.9051, 0.1220, 0.4290, 0.0770],
        [0.5799, 0.6340, 0.8380, 0.6840]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [80]:
# Let's make some random but reproducible tensors

# Set the random seed
Random_seed = 42

torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Check for the GPU access in the pytorch


In [81]:
# Running tensors and PyTorch objects on gpu (and making faster computations)
!nvidia-smi

Mon Jul  7 18:52:31 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [82]:
# Check for the GPU access with PyTorch
torch.cuda.is_available()

True

In [83]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [84]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting the tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because4 using a GPU results in faster computations

In [85]:
# Create a tesnor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device = "cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [95]:
# If tensor is on GPU, can't transform it to Numpy
# tensor_on_gpu.numpy()

In [94]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.device

device(type='cpu')