<a href="https://colab.research.google.com/github/kavyarajegoist/deep_learning_with_pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
### Creating Tensors
Pytorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([2, 3])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[1,3,4],[2,3,3]]])
TENSOR

tensor([[[1, 2, 3],
         [1, 3, 4],
         [2, 3, 3]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 3, 4],
        [2, 3, 3]])

In [16]:
TENSOR[0][1]

tensor([1, 3, 4])

In [17]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learns as they start with tensors full of random numbers and then adjust those random numbers to better represnt the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
#create a random tensor of size(3,3)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7772, 0.3131, 0.2178, 0.3530],
        [0.3068, 0.9610, 0.1984, 0.5500],
        [0.3162, 0.8978, 0.4506, 0.9375]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
#Create a random tensor with similar to shape of and image tensor
random_image_size_tensor = torch.rand(size =(224,224,3) ) # height , width , color channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor


In [22]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create all tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
#Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big error you'll run into  with Pytorch & deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

Precision in computing


In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what datatype is the tensor (eg.float32))
                                  device = None,# What device is your tensor on
                               requires_grad=False) #whether or not to track gradient with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])




### Getting information from tensors
1. Tensor not right datatype. - to do get datatype from a tensor, can use 'tensor.dtype'.
2. Tensor not right shape. - to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use tensor.device






In [46]:
#Create a tensor
some_tensor = torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.1328, 0.7637, 0.8994, 0.8750],
        [0.3809, 0.2500, 0.1606, 0.7241],
        [0.2466, 0.7085, 0.3604, 0.9595]], dtype=torch.float16)

In [47]:
print(f"Data type of tensor: {some_tensor.dtype}")
print(some_tensor.shape)
print(some_tensor.device)

Data type of tensor: torch.float16
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operation)

* Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication


In [63]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [64]:
tensor - 5

tensor([-4, -3, -2])

In [65]:
tensor * 10


tensor([10, 20, 30])

In [66]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [67]:
#Tensor inbuilt function
torch.mul(tensor,10)


tensor([10, 20, 30])