<a href="https://colab.research.google.com/github/kavyarajegoist/deep_learning_with_pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
### Creating Tensors
Pytorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([2, 3])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[1,3,4],[2,3,3]]])
TENSOR

tensor([[[1, 2, 3],
         [1, 3, 4],
         [2, 3, 3]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 3, 4],
        [2, 3, 3]])

In [16]:
TENSOR[0][1]

tensor([1, 3, 4])

In [17]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learns as they start with tensors full of random numbers and then adjust those random numbers to better represnt the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
#create a random tensor of size(3,3)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9255, 0.9745, 0.2506, 0.4788],
        [0.6012, 0.5599, 0.3835, 0.2147],
        [0.3386, 0.7743, 0.6443, 0.4897]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
#Create a random tensor with similar to shape of and image tensor
random_image_size_tensor = torch.rand(size =(224,224,3) ) # height , width , color channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor


In [22]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create all tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
#Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note:** Tensor datatype is one of the 3 big error you'll run into  with Pytorch & deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

Precision in computing


In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what datatype is the tensor (eg.float32))
                                  device = None,# What device is your tensor on
                               requires_grad=False) #whether or not to track gradient with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])




### Getting information from tensors
1. Tensor not right datatype. - to do get datatype from a tensor, can use 'tensor.dtype'.
2. Tensor not right shape. - to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use tensor.device






In [33]:
#Create a tensor
some_tensor = torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.6206, 0.7583, 0.6060, 0.0962],
        [0.9834, 0.9082, 0.1646, 0.5850],
        [0.5269, 0.0352, 0.0508, 0.4409]], dtype=torch.float16)

In [34]:
print(f"Data type of tensor: {some_tensor.dtype}")
print(some_tensor.shape)
print(some_tensor.device)

Data type of tensor: torch.float16
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operation)

* Tensor operation include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication


In [35]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor - 5

tensor([-4, -3, -2])

In [37]:
tensor * 10


tensor([10, 20, 30])

In [38]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [39]:
#Tensor inbuilt function
torch.mul(tensor,10)


tensor([10, 20, 30])

### Matrix Multiplication
Two ways of matrix multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [40]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [41]:
#Matrics Multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 501 µs, total: 501 µs
Wall time: 6.75 ms


tensor(14)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 814 µs, sys: 0 ns, total: 814 µs
Wall time: 954 µs


In [43]:
# Shapes for matrix multiplication
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])



To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.

In [44]:
tensorB.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [45]:
torch.mm(tensorA,tensorB.T).shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc.(tensor aggregation)


In [46]:
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [47]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [49]:
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [51]:
# Finding the positional min and max value(basically finding the index)
x.argmin()

tensor(0)

In [52]:
x.argmax()

tensor(9)

In [53]:
x[9]

tensor(90)

In [54]:
%%time
l = [1,2,3]
value = 0
for i in range(len(l)):
  value += l[i] * l[i]
print(value)

14
CPU times: user 305 µs, sys: 0 ns, total: 305 µs
Wall time: 322 µs


## Reshaping, stacking, squeezing and unsqueezing tesnors

* Reshaping - reshapes an input tensor  to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine mutiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - remove all `1` dimensions from a tensor

* Unsqueeze - adds `1` dimensions to a tensor

* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [55]:
#let create tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
# Add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# Change the view
z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# Changing z changes x (because a view of a tensor share the same memory as the original tensor)
z[:,0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [61]:
# torch.unsqueeze() add a single dimensions to a target at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous target shpae: {x_squeezed.shape}")

x_unsqueezed = torch.unsqueeze(x_squeezed,0)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous target shpae: torch.Size([9])

New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [62]:
#torch.prmute - rearranges the dimesions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # (height, width, colour_channels)
x_permuted = torch.permute(x_original,dims=(2,0,1))

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [63]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
x[0][0],x[0,0],x[0,0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]), tensor(1))

In [65]:
# Challenge to get the number 9
x[0][2][2]

tensor(9)

In [66]:
# Using ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of 0th dimensions but only index 1 of 2nd dimensions
x[:,:,1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of 0th dimensions but only the 1 index of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [69]:
# Get index o of 0th and 1st dimension and all values of 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

In [80]:
# index on x to return 9
x[:,2,2]

tensor([9])

In [93]:
# return 3,6,9
x[0,:3,2]

tensor([3, 6, 9])