<a href="https://colab.research.google.com/github/kavyarajegoist/deep_learning_with_pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors
### Creating Tensors
Pytorch tensors are created using `torch.tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [31]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [32]:
scalar.ndim


0

In [33]:
#Get tensor back as Python int
scalar.item()

7

In [34]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([2])

In [37]:
#MATRIX
MATRIX = torch.tensor([[7,8],[2,3]])
MATRIX

tensor([[7, 8],
        [2, 3]])

In [38]:
MATRIX[0]

tensor([7, 8])

In [39]:
MATRIX[1]

tensor([2, 3])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[1,3,4],[2,3,3]]])
TENSOR

tensor([[[1, 2, 3],
         [1, 3, 4],
         [2, 3, 3]]])

In [42]:
TENSOR.shape

torch.Size([1, 3, 3])

In [43]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 3, 4],
        [2, 3, 3]])

In [44]:
TENSOR[0][1]

tensor([1, 3, 4])

In [45]:
TENSOR.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learns as they start with tensors full of random numbers and then adjust those random numbers to better represnt the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> update random numbers`

In [46]:
#create a random tensor of size(3,3)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1261, 0.4537, 0.4697, 0.6128],
        [0.6164, 0.5781, 0.2351, 0.1391],
        [0.0157, 0.8227, 0.5185, 0.5079]])

In [47]:
random_tensor.ndim

2

In [48]:
random_tensor.shape

torch.Size([3, 4])

In [49]:
#Create a random tensor with similar to shape of and image tensor
random_image_size_tensor = torch.rand(size =(224,224,3) ) # height , width , color channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones Tensor


In [50]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
#Create all tensors of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [55]:
#Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
#Creating tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes